name: seattledata1
channels:
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.11
  - pip

  # Data + numerics
  - numpy
  - pandas
  - pyarrow

  # Plotting
  - matplotlib
  - seaborn

  # ML (sklearn IsolationForest, LabelEncoder)
  - scikit-learn

  # Notebooks / widgets
  - jupyterlab
  - ipykernel
  - ipywidgets

  # Optional but nice to have
  - python-dateutil
  - pytz

  - pip:
      # Spark + XGBoost (SparkXGBRegressorModel)
      - pyspark==4.0.1
      - xgboost==2.1.1

      # Dashboard + plotting
      - streamlit==1.51.0
      - plotly

      # Download helper
      - gdown